# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Force Engine
tagline:          'TBA'
description:      'TBA'
url:              https://TheForceEngine.github.io
baseurl:          https://TheForceEngine.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://TheForceEngine.github.io

