# Setup
title:            The Force Engine
tagline:          'Tag TBA'
description:      'Description'
url:              https://TheForceEngine.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'luciusDXL'
  url:            ''

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
