# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Force Engine
tagline:          'TBA'
description:      'TBA'
url:              https://TheForceEngine.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://TheForceEngine.github.io

