# Setup
title:            The Force Engine
tagline:          ''
description:      'Modern "Jedi Engine" replacement supporting Dark Forces and the mods.'
url:              https://TheForceEngine.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'luciusDXL'
  url:            ''

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0

# Google Analytics
google_analytics: G-5TNXZGGZ1J

# Includes
include: [".well-known"]
